print("Welcome to Bot Invitation Maker!")
BOT_ID = input("Enter your bot's Client ID (CTRL + V to paste.): ")
print("Preparing link...")
print("https://discord.com/oauth2/authorize?client_id=" + BOT_ID + "&scope=bot&permissions=8" + " (CTRL + C to copy.)")
print("Thanks for using Bot Invitation Maker.")
input()
