print("Bot Invitation Maker'a hoşgeldiniz!")
BOT_ID = input("Botunuzun Client ID'sini giriniz (Yapıştırmak için CTRL + V): ")
print("Link hazırlanıyor...")
print("https://discord.com/oauth2/authorize?client_id=" + BOT_ID + "&scope=bot&permissions=8" + " (Kopyalamak için CTRL + C)")
print("Bot Invitation Maker'ı kullandığınız için teşekkür ederiz.")
input()
